LM_init: false
ablation_strategies:
- zero
- random
- none
backbone: BERT_small
batch_size_list:
- 64
check_val_every_n_epoch: 1
ckpt_period: 1
data_dir: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Data/Language
dataset: SyntaxDataModule
early_stopping: 0
es_patience: 0
evaluation_type: test
exp_dir: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Language/Models/SV_Agr_Singular/BERT_Small_LM/Mask_Training/da4466e3-3b9d-4932-af62-a8d548906254_T1
freeze_until: -1
gpus: 1
l0_components:
  backbone: true
l0_init_list:
- 0.0
l0_lambda: 1.0e-08
l0_stage_list:
- 0
log_every_n_steps: 100
lr_list:
- 0.0001
max_epochs: 90
max_temp: 200
model: BERT_small
num_workers: 1
pretrained_weights:
  backbone: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Language/Models/SV_Agr_Singular/BERT_Small_LM/Model_Training/da4466e3-3b9d-4932-af62-a8d548906254_backbone.pt
refresh_rate: 10
results_dir: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Language/Results/SV_Agr_Singular/BERT_Small_LM/Mask_Training/da4466e3-3b9d-4932-af62-a8d548906254_T1
save_models: true
seed_list:
- 0
- 1
- 2
test_set: ''
test_tasks:
- '0'
- '1'
- '2'
- '3'
- '4'
train_masks:
  backbone: true
train_task: '1'
train_transform: null
train_weights:
  backbone: false
use_last: true
val_transform: null
wd: 0.0
