ablation_strategies:
- none
- zero
backbone: resnet50
batch_size_list:
- 64
check_val_every_n_epoch: 1
ckpt_period: 1
data_dir: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Data/Vision/
dataset: CVRTDataModule
early_stopping: 0
es_patience: 0
evaluation_type: test
exp_dir: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Vision/Models/Count_Contact/Resnet50_SimCLR/L0_Reporting/c837016c-fe1e-4306-8782-7b0ad0037564_T116
gpus: 1
l0_components:
  backbone: true
  mlp: true
l0_init_list:
- 0.05
l0_lambda: 1.0e-08
l0_stage_list:
- - stage_3
  - stage_4
log_every_n_steps: 100
lr_list:
- 0.01
max_epochs: 0
max_temp: 200
mlp_dim: 128
mlp_hidden_dim: 2048
n_samples: 10000
n_tasks: 1
num_workers: 1
pretrained_weights:
  backbone: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Vision/Models/Count_Contact/Resnet50_SimCLR/Mask_Training/c837016c-fe1e-4306-8782-7b0ad0037564_T116/e6e95f43-56a7-4b07-bf7c-b698a0d3d5d5_backbone.pt
  embedding: false
  mlp: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Vision/Models/Count_Contact/Resnet50_SimCLR/Mask_Training/c837016c-fe1e-4306-8782-7b0ad0037564_T116/e6e95f43-56a7-4b07-bf7c-b698a0d3d5d5_mlp.pt
refresh_rate: 10
results_dir: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Vision/Results/Count_Contact/Resnet50_SimCLR/L0_Reporting/c837016c-fe1e-4306-8782-7b0ad0037564_T116/e6e95f43-56a7-4b07-bf7c-b698a0d3d5d5_backbone.pt
save_models: false
seed_list:
- 0
task_embedding: 0
test_set: ''
test_tasks:
- '115'
train_masks:
  backbone: false
  mlp: false
train_task: '116'
train_transform: null
train_weights:
  backbone: false
  embedding: false
  mlp: false
use_last: true
val_transform: null
wd: 0.0
