model: 'BERT_small'
dataset: 'SyntaxDataModule'
# trainer
gpus: 1
max_epochs: 5
num_workers: 1
log_every_n_steps: 100
ckpt_period: 1
seed_list: [0]
early_stopping: 1
refresh_rate: 10
es_patience: 30
check_val_every_n_epoch: 1
#arch
backbone: 'BERT_small'
lr_list: [0.0001]
wd: 0.00
# data 
data_dir: '/users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Data/Language'
train_task: '5'
test_tasks: ['5', '6', '7', '8', '9']
batch_size_list: [32]
train_transform: null
val_transform: null
test_set: ''
exp_dir: '/users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Language/Models/Model_Reporting'
results_dir: '/users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Language/Results/Model_Reporting'

# Config variables introduced for mask identification
l0_components: {"backbone": True}
train_masks: {"backbone": True}
train_weights: {"backbone": False}
pretrained_weights: { 
  "backbone": False,
  } # False for random initialization
l0_init_list: [0.0]
l0_lambda: 0.00000001
max_temp: 100
l0_stage_list: [3]
ablation_strategies: ["None"]
evaluation_type: "test"
LM_init: False # Denotes whether to initialize the model with pretrained LM parameters
freeze_until: -1
save_models: False
use_last: False
