path_db: '../Subnetworks_db/rn18'
model: 'CNN'
dataset: 'CVRTDataModule'
# trainer
gpus: 1
max_epochs: 200
num_workers: 4
checkpoint: ''
finetune: 0
freeze_pretrained: 0
log_every_n_steps: 100
ckpt_period: 1
seed: 0
early_stopping: 1
refresh_rate: 10
es_patience: 20
check_val_every_n_epoch: 1
#arch
backbone: 'resnet18'
lr: 0.00001
wd: 0.00
n_tasks: 1
mlp_dim: 128
mlp_hidden_dim: 2048
task_embedding: 0
# data
data_dir: '/media/data_cifs_lrs/projects/prj_visreason/cvrt_data/'
task: '8' # Denotes multitask training
batch_size: 64
train_transform: null
val_transform: null
n_samples: 10000 # 5000, 1000
test_set: ''
exp_name: "RN18_Training_Contact"
exp_dir: '../Subnetworks_db/rn18/RN18_MT_Training_Contact'
