path_db: '../Subnetworks_db/l0'
model: 'CNN'
dataset: 'CVRTDataModule'
# trainer
gpus: 1
max_epochs: 200
num_workers: 4
checkpoint: ''
finetune: 0
freeze_pretrained: 0
log_every_n_steps: 100
ckpt_period: 1
seed: 0
early_stopping: 1
refresh_rate: 10
es_patience: 1
check_val_every_n_epoch: 1
#arch
backbone: 'L0mlp'
lr: 0.00001
wd: 0.00
n_tasks: 2
mlp_dim: 128
mlp_hidden_dim: 2048
task_embedding: 64
# data
data_dir: '/media/data_cifs_lrs/projects/prj_visreason/cvrt_data/'
task: '2-3' # Denotes multitask training
batch_size: 64
train_transform: null
val_transform: null
n_samples: 10000 # 5000, 1000
test_set: ''
exp_name: "L0_MT_Training"
exp_dir: '../Subnetworks_db/l0/L0_MT_Training'
pretrained_model_path: '../Subnetworks_db/mlp/MLP_MT_Training/last.ckpt'
pretrained_model: 'L0mlp'
train_mask: True
l0_init: -0.1
l0_lambda: 1E-8
max_temp: 200

