path_db: '../Subnetworks_db/lenet'
model: 'CNN'
dataset: 'CVRTDataModule'
# trainer
gpus: 1
max_epochs: 30
num_workers: 4
checkpoint: ''
finetune: 0
freeze_pretrained: 0
log_every_n_steps: 100
ckpt_period: 1
seed: 0
early_stopping: 1
refresh_rate: 10
es_patience: 3
check_val_every_n_epoch: 1
#arch
backbone: 'lenet'
lr: 0.001
wd: 0.00
n_tasks: 1
mlp_dim: 128
mlp_hidden_dim: 256
task_embedding: 0
# data
data_dir: '/media/data_cifs_lrs/projects/prj_visreason/cvrt_data/'
task: '24' # Denotes multitask training
batch_size: 64
train_transform: null
val_transform: null
n_samples: 10000 # 5000, 1000
test_set: ''
exp_name: "LeNet_Comp_Training"
exp_dir: '../Subnetworks_db/lenet/LeNet_Comp_Training'

# Config variables introduced for mask identification
l0_components: {"backbone": False, "mlp": False}
train_masks: {"backbone": False, "mlp": False}
train_weights: {"backbone": True, "mlp": True, "embedding": False}
pretrained_weights: { 
  "backbone": False,
  "mlp": False,
  "embedding": False
  } # False for random initialization
l0_init: 0.0
l0_lambda: .00000001
max_temp: 200
eval_only: False # This is derivable from train_masks and train_weights, but make it explicit with another variable
