path_db: '../Subnetworks_db/lenet'
model: 'CNN'
dataset: 'CVRTDataModule'
# trainer
gpus: 1
max_epochs: 90
num_workers: 4
checkpoint: ''
finetune: 0
freeze_pretrained: 0
log_every_n_steps: 100
ckpt_period: 1
seed: -1
early_stopping: 0
refresh_rate: 10
es_patience: 20
check_val_every_n_epoch: 1
#arch
backbone: 'lenet'
lr: 0.0001
wd: 0.00
n_tasks: 0
mlp_dim: 128
mlp_hidden_dim: 256
task_embedding: 0
# data
data_dir: '/media/data_cifs_lrs/projects/prj_visreason/cvrt_data/'
task: '1' # Denotes multitask training
batch_size: 64
train_transform: null
val_transform: null
n_samples: 10000 # 5000, 1000
test_set: ''
exp_name: "LeNet_Position_Subnetwork"
exp_dir: '../Subnetworks_db/lenet/LeNet_Position_Subnetwork'
pretrained_backbone_path: '../Subnetworks_db/lenet/LeNet_Comp_Training/backbone.pt'
pretrained_mlp_path: '../Subnetworks_db/lenet/LeNet_Comp_Training/mlp.pt'
train_mask: True
l0_init: -0.1
l0_lambda: .00000001 #1E-8
max_temp: 200
l0_mlp: True
eval_only: False
