ablation_strategies:
- zero
- random
- none
backbone: resnet50
batch_size_list:
- 64
check_val_every_n_epoch: 1
ckpt_period: 1
data_dir: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Data/Vision/
dataset: CVRTDataModule
early_stopping: 0
es_patience: 0
evaluation_type: test
exp_dir: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Vision/Models/Count_Contact/Resnet50/Pruned_Mask_Training/ # Append to this
gpus: 1
l0_components:
  backbone: true
  mlp: true
l0_init_list: [] # Set this
l0_lambda: 1.0e-08
l0_stage_list: [] # Set this
log_every_n_steps: 100
lr_list: [] # Set this
max_epochs: 90
max_temp: 200
mlp_dim: 128
mlp_hidden_dim: 2048
n_samples: 10000
n_tasks: 1
num_workers: 1
pretrained_weights:
  backbone: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Vision/Models/Count_Contact/Resnet50/Pruning_Training/ # append to this
  embedding: false
  mlp: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Vision/Models/Count_Contact/Resnet50/Pruning_Training/ # append to this
refresh_rate: 10
results_dir: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Vision/Results/Count_Contact/Resnet50/Pruned_Mask_Training/ # Append to this
save_models: true
seed_list:
- 0
- 1
- 2
task_embedding: 0
test_set: ''
test_tasks:
- '115'
- '116'
- '117'
- '118'
- '119'
- '120'
train_masks:
  backbone: true
  mlp: true
train_task: null # set this
train_transform: null
train_weights:
  backbone: false
  embedding: false
  mlp: false
use_last: true
val_transform: null
wd: 0.0
