LM_init: false
ablation_strategies:
- zero
- random
- none
backbone: BERT_small
batch_size: 64
check_val_every_n_epoch: 1
ckpt_period: 1
data_dir: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Data/Language
dataset: SyntaxDataModule
early_stopping: 0
es_patience: 30
evaluation_type: validate
exp_dir: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Language/Models/BERT_Small/SVAgr_S_Iter_Experiments/BERT_Small_model2_T1_2startStage
freeze_until: -1
gpus: 1
l0_components:
  backbone: true
l0_init: -0.05
l0_lambda: 1.0e-08
l0_stages: 2
log_every_n_steps: 100
lr: 0.01
max_epochs: 90
max_temp: 200
model: BERT_small
num_workers: 1
pretrained_weights:
  backbone: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Language/Models/BERT_Small/SVAgr_S_Models/2_backbone.pt
prune_iterations: 5
refresh_rate: 10
results_dir: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Language/Results/BERT_Small/SVAgr_S_Iter_Experiments/BERT_Small_model2_T1_2startStage
save_models: false
seed_list:
- 1
test_set: ''
test_tasks:
- '0'
- '1'
- '2'
- '3'
- '4'
train_masks:
  backbone: true
train_task: '1'
train_transform: null
train_weights:
  backbone: false
use_last: true
val_transform: null
wd: 0.0
