model: 'BERT_small'
dataset: 'SyntaxDataModule'
# trainer
gpus: 1
max_epochs: 100
num_workers: 1
log_every_n_steps: 100
ckpt_period: 1
seed_list: [0, 1, 2]
early_stopping: 1
refresh_rate: 10
es_patience: 30
check_val_every_n_epoch: 1
#arch
backbone: 'BERT_small'
lr_list: [0.0001]
wd: 0.00
# data 
data_dir: '/users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Data/Language'
train_task: '15'
test_tasks: ['15', '16', '17', '18', '19']
batch_size_list: [64]
train_transform: null
val_transform: null
test_set: ''
exp_dir: '/users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Language/Models/Anaphora_Plural/BERT_Small/Model_Training'
results_dir: '/users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Language/Results/Anaphora_Plural/BERT_Small/Model_Training'

# Config variables introduced for mask identification
l0_components: {"backbone": False}
train_masks: {"backbone": False}
train_weights: {"backbone": True}
pretrained_weights: { 
  "backbone": False,
  } # False for random initialization
l0_init_list: [-1]
l0_lambda: -1
max_temp: -1
l0_stage_list: [-1]
ablation_strategies: ["None"]
evaluation_type: "test"
LM_init: False # Denotes whether to initialize the model with pretrained LM parameters
freeze_until: -1
save_models: True
use_last: False
