LM_init: false
ablation_strategies:
- zero
- random
- none
backbone: BERT_small
batch_size_list:
- 64
check_val_every_n_epoch: 1
ckpt_period: 1
data_dir: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Data/Language
dataset: SyntaxDataModule
early_stopping: 0
es_patience: 0
evaluation_type: validate
exp_dir: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Language/Models/Anaphora_Singular/BERT_Small/Mask_Parameters/8b9a5996-bf37-4b29-bf63-364295d9dda3/12/T12_0.1_0stage
freeze_until: -1
gpus: 1
l0_components:
  backbone: true
l0_init_list:
- 0.1
l0_lambda: 1.0e-08
l0_stage_list:
- 0
log_every_n_steps: 100
lr_list:
- 0.01
- 0.0001
max_epochs: 90
max_temp: 200
model: BERT_small
num_workers: 1
pretrained_weights:
  backbone: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Language/Models/Anaphora_Singular/BERT_Small/Model_Training/8b9a5996-bf37-4b29-bf63-364295d9dda3_backbone.pt
refresh_rate: 10
results_dir: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Language/Results/Anaphora_Singular/BERT_Small/Mask_Parameters/8b9a5996-bf37-4b29-bf63-364295d9dda3/12/T12_0.1_0stage
save_models: false
seed_list:
- 0
test_set: ''
test_tasks:
- '10'
- '11'
- '12'
- '13'
- '14'
train_masks:
  backbone: true
train_task: '12'
train_transform: null
train_weights:
  backbone: false
use_last: true
val_transform: null
wd: 0.0
