ablation_strategies:
- zero
- random
- none
backbone: resnet50
batch_size_list:
- 64
check_val_every_n_epoch: 1
ckpt_period: 1
data_dir: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Data/Vision/
dataset: CVRTDataModule
early_stopping: 0
es_patience: 0
evaluation_type: test
exp_dir: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Vision/Models/Inside_Contact/Resnet50/Pruned_Mask_Training/48addbb7-af74-4b08-b75d-9b0c593df9fe_T105
gpus: 1
l0_components:
  backbone: true
  mlp: true
l0_init_list:
- -0.05
l0_lambda: 1.0e-08
l0_stage_list:
- - stage_4
log_every_n_steps: 100
lr_list:
- 0.01
max_epochs: 90
max_temp: 200
mlp_dim: 128
mlp_hidden_dim: 2048
n_samples: 10000
n_tasks: 1
num_workers: 1
pretrained_weights:
  backbone: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Vision/Models/Inside_Contact/Resnet50/Pruning_Training/b80c24dc-266d-4c4d-9967-ee59215ca185_T103/48addbb7-af74-4b08-b75d-9b0c593df9fe_backbone.pt
  embedding: false
  mlp: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Vision/Models/Inside_Contact/Resnet50/Pruning_Training/b80c24dc-266d-4c4d-9967-ee59215ca185_T103/48addbb7-af74-4b08-b75d-9b0c593df9fe_mlp.pt
refresh_rate: 10
results_dir: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Vision/Results/Inside_Contact/Resnet50/Pruned_Mask_Training/48addbb7-af74-4b08-b75d-9b0c593df9fe_T105
save_models: true
seed_list:
- 0
- 1
- 2
task_embedding: 0
test_set: ''
test_tasks:
- '103'
- '104'
- '105'
- '106'
- '107'
- '108'
train_masks:
  backbone: true
  mlp: true
train_task: '105'
train_transform: null
train_weights:
  backbone: false
  embedding: false
  mlp: false
use_last: true
val_transform: null
wd: 0.0
