ablation_strategies:
- none
- zero
backbone: wideresnet50
batch_size_list:
- 64
check_val_every_n_epoch: 1
ckpt_period: 1
data_dir: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Data/Vision/
dataset: CVRTDataModule
early_stopping: 0
es_patience: 0
evaluation_type: test
exp_dir: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Vision/Models/Count_Contact/WideResnet50/L0_Reporting/f4f21ca4-942b-4f6b-9166-26a9bec253a9_T116
gpus: 1
l0_components:
  backbone: true
  mlp: true
l0_init_list:
- 0.1
l0_lambda: 1.0e-08
l0_stage_list:
- - stage_4
log_every_n_steps: 100
lr_list:
- 0.0001
max_epochs: 0
max_temp: 200
mlp_dim: 128
mlp_hidden_dim: 2048
n_samples: 10000
n_tasks: 1
num_workers: 1
pretrained_weights:
  backbone: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Vision/Models/Count_Contact/WideResnet50/Mask_Training/f4f21ca4-942b-4f6b-9166-26a9bec253a9_T116/c368a756-f7ef-4e70-968e-bdbb4b0139b4_backbone.pt
  embedding: false
  mlp: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Vision/Models/Count_Contact/WideResnet50/Mask_Training/f4f21ca4-942b-4f6b-9166-26a9bec253a9_T116/c368a756-f7ef-4e70-968e-bdbb4b0139b4_mlp.pt
refresh_rate: 10
results_dir: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Vision/Results/Count_Contact/WideResnet50/L0_Reporting/f4f21ca4-942b-4f6b-9166-26a9bec253a9_T116/c368a756-f7ef-4e70-968e-bdbb4b0139b4_backbone.pt
save_models: false
seed_list:
- 0
task_embedding: 0
test_set: ''
test_tasks:
- '115'
train_masks:
  backbone: false
  mlp: false
train_task: '116'
train_transform: null
train_weights:
  backbone: false
  embedding: false
  mlp: false
use_last: true
val_transform: null
wd: 0.0
