base_dir: '/users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Language/Results/Anaphora_Singular/BERT_Small/Mask_Training'
hypothesized_performance: {
  '11' : {
    'high_after_ablation' : '13',
    'low_after_ablation' : '14'
  },
  '12' : {
    'high_after_ablation' : '14',
    'low_after_ablation' : '13'
  }
}
model: "BERT Small"