path_db: '../gen_ebm_db/lat_ebm'
model: 'CNN_VAE'
dataset: 'SVHNSupDataModule'
# trainer
gpus: 1
max_epochs: 200
num_workers: 4
flush_logs_every_n_steps: 100
log_every_n_steps: 100
ckpt_period: 3
# model
learning_rate: 0.001
#arch
input_height: 32
input_dim: 3
hidden_dim: 64
latent_dim: 128
activation: 'relu'
activation_leak: 0.2
batchnorm: false
kl_coeff: 1
lr: 0.001
# data
data_dir: '../data/SVHN'
batch_size: 128
train_transform: null
val_transform: null
num_val: 1000