ablation_strategies:
- zero
- random
- none
backbone: L0wideresnet50
batch_size_list:
- 64
calibration_task: '103'
check_val_every_n_epoch: 1
ckpt_period: 1
data_dir: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Data/
dataset: CVRTDataModule
early_stopping: 0
es_patience: 0
exp_dir: /users/mlepori/scratch/Compositional_Subnetworks/Models/wide_resnet50/Contact_Inside_Experiments/WRN50_model3_T105_0.05_3stage
gpus: 1
l0_components:
  backbone: true
  mlp: true
l0_init_list:
- 0.05
l0_lambda: 1.0e-08
l0_stage_list:
- - stage_2
  - stage_3
  - stage_4
log_every_n_steps: 100
lr_list:
- 0.01
- 0.0001
max_epochs: 90
max_temp: 200
mlp_dim: 128
mlp_hidden_dim: 2048
model: CNN
n_samples: 10000
n_tasks: 1
num_workers: 1
pretrained_weights:
  backbone: /users/mlepori/scratch/Compositional_Subnetworks/Models/wide_resnet50/ConIn_Models/3_backbone.pt
  embedding: false
  mlp: /users/mlepori/scratch/Compositional_Subnetworks/Models/wide_resnet50/ConIn_Models/3_mlp.pt
refresh_rate: 10
results_dir: /users/mlepori/scratch/Compositional_Subnetworks/Results/wide_resnet50/Contact_Inside_Experiments/WRN50_model3_T105_0.05_3stage
save_models: false
seed_list:
- 1
- 2
- 3
task_embedding: 0
test_set: ''
test_tasks:
- '103'
- '104'
- '105'
- '106'
- '107'
- '108'
train_masks:
  backbone: true
  mlp: true
train_task: '105'
train_transform: null
train_weights:
  backbone: false
  embedding: false
  mlp: false
use_last: true
val_transform: null
wd: 0.0
