LM_init: false
ablation_strategies:
- none
- zero
backbone: BERT_small
batch_size_list:
- 64
check_val_every_n_epoch: 1
ckpt_period: 1
data_dir: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Data/Language
dataset: SyntaxDataModule
early_stopping: 0
es_patience: 0
evaluation_type: test
exp_dir: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Language/Models/SV_Agr_Plural/BERT_Small/L0_Reporting/3d4f38b3-7abf-46ba-9eca-3befdd298b2d_T6
freeze_until: -1
gpus: 1
l0_components:
  backbone: true
l0_init_list:
- 0.0
l0_lambda: 1.0e-08
l0_stage_list:
- 0
log_every_n_steps: 100
lr_list:
- 0.0001
max_epochs: 0
max_temp: 200
model: BERT_small
num_workers: 1
pretrained_weights:
  backbone: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Language/Models/SV_Agr_Plural/BERT_Small/Mask_Training/3d4f38b3-7abf-46ba-9eca-3befdd298b2d_T6/26c174fa-6313-444d-ab78-91f73d643797_backbone.pt
refresh_rate: 10
results_dir: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Language/Results/SV_Agr_Plural/BERT_Small/L0_Reporting/3d4f38b3-7abf-46ba-9eca-3befdd298b2d_T6/26c174fa-6313-444d-ab78-91f73d643797_backbone.pt
save_models: false
seed_list:
- 0
test_set: ''
test_tasks:
- '1'
train_masks:
  backbone: false
  mlp: false
train_task: '6'
train_transform: null
train_weights:
  backbone: false
use_last: true
val_transform: null
wd: 0.0
