LM_init: false
ablation_strategies:
- none
- zero
backbone: BERT_small
batch_size_list:
- 64
check_val_every_n_epoch: 1
ckpt_period: 1
data_dir: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Data/Language
dataset: SyntaxDataModule
early_stopping: 0
es_patience: 0
evaluation_type: test
exp_dir: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Language/Models/SV_Agr_Plural/BERT_Small/L0_Reporting/2f6a349f-d1a1-41b7-bcf7-fbaff3eadc24_T7
freeze_until: -1
gpus: 1
l0_components:
  backbone: true
l0_init_list:
- 0.05
l0_lambda: 1.0e-08
l0_stage_list:
- 2
log_every_n_steps: 100
lr_list:
- 0.0001
max_epochs: 0
max_temp: 200
model: BERT_small
num_workers: 1
pretrained_weights:
  backbone: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Language/Models/SV_Agr_Plural/BERT_Small/Mask_Training/2f6a349f-d1a1-41b7-bcf7-fbaff3eadc24_T7/a3de3819-5b6e-4480-bb6d-12d6800cd416_backbone.pt
refresh_rate: 10
results_dir: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Language/Results/SV_Agr_Plural/BERT_Small/L0_Reporting/2f6a349f-d1a1-41b7-bcf7-fbaff3eadc24_T7/a3de3819-5b6e-4480-bb6d-12d6800cd416_backbone.pt
save_models: false
seed_list:
- 0
test_set: ''
test_tasks:
- '1'
train_masks:
  backbone: false
  mlp: false
train_task: '7'
train_transform: null
train_weights:
  backbone: false
use_last: true
val_transform: null
wd: 0.0
