ablation_strategies:
- none
backbone: resnet50
evaluation_type: test
gpus: 1
l0_components:
  backbone: true
  mlp: true
l0_init: 0.1
l0_lambda: 1.0e-08
l0_stages:
- stage_3
- stage_4
max_temp: 200
mlp_dim: 128
mlp_hidden_dim: 2048
num_workers: 1
pretrained_weights_list:
  - backbone: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Vision/Models/Inside_Count/Resnet50/Mask_Training/0432d0b8-1719-478c-826c-5b18771f6b91_T111/6ca13153-dbed-4418-b399-ad3d77c5e636_backbone.pt
    embedding: false
    mlp: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Vision/Models/Inside_Count/Resnet50/Mask_Training/0432d0b8-1719-478c-826c-5b18771f6b91_T111/6ca13153-dbed-4418-b399-ad3d77c5e636_mlp.pt

  - backbone: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Vision/Models/Inside_Count/Resnet50/Mask_Training/0432d0b8-1719-478c-826c-5b18771f6b91_T111/75f7e74b-2079-4c99-ae00-75e3c00df2d0_backbone.pt
    embedding: false
    mlp: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Vision/Models/Inside_Count/Resnet50/Mask_Training/0432d0b8-1719-478c-826c-5b18771f6b91_T111/75f7e74b-2079-4c99-ae00-75e3c00df2d0_mlp.pt

  - backbone: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Vision/Models/Inside_Count/Resnet50/Mask_Training/0432d0b8-1719-478c-826c-5b18771f6b91_T111/98a4c45d-9717-4f35-9d0d-834f7e19fe1a_backbone.pt
    embedding: false
    mlp: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Vision/Models/Inside_Count/Resnet50/Mask_Training/0432d0b8-1719-478c-826c-5b18771f6b91_T111/98a4c45d-9717-4f35-9d0d-834f7e19fe1a_mlp.pt
  
task_embedding: 0
train_masks:
  backbone: false
  mlp: false
train_weights:
  backbone: false
  embedding: false
  mlp: false
wd: 0.0
