ablation_strategies:
- none
backbone: resnet50
evaluation_type: test
gpus: 1
l0_components:
  backbone: true
  mlp: true
l0_init: 0.1
l0_lambda: 1.0e-08
l0_stages:
- stage_4
max_temp: 200
mlp_dim: 128
mlp_hidden_dim: 2048
pretrained_weights_list:
  - backbone: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Vision/Models/Inside_Count/Resnet50/Mask_Training/883cd15e-cf44-43bd-8fe9-56a91090aef7_T111/b9fee16a-702e-4613-af51-43b44359a903_backbone.pt
    embedding: false
    mlp: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Vision/Models/Inside_Count/Resnet50/Mask_Training/883cd15e-cf44-43bd-8fe9-56a91090aef7_T111/b9fee16a-702e-4613-af51-43b44359a903_mlp.pt

  - backbone: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Vision/Models/Inside_Count/Resnet50/Mask_Training/883cd15e-cf44-43bd-8fe9-56a91090aef7_T111/d58dada9-05df-413c-8aa8-c79af8987070_backbone.pt
    embedding: false
    mlp: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Vision/Models/Inside_Count/Resnet50/Mask_Training/883cd15e-cf44-43bd-8fe9-56a91090aef7_T111/d58dada9-05df-413c-8aa8-c79af8987070_mlp.pt

  - backbone: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Vision/Models/Inside_Count/Resnet50/Mask_Training/883cd15e-cf44-43bd-8fe9-56a91090aef7_T111/d3487469-fd62-4d57-b581-a8d580cfad76_backbone.pt
    embedding: false
    mlp: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Vision/Models/Inside_Count/Resnet50/Mask_Training/883cd15e-cf44-43bd-8fe9-56a91090aef7_T111/d3487469-fd62-4d57-b581-a8d580cfad76_mlp.pt

task_embedding: 0
train_masks:
  backbone: false
  mlp: false
train_weights:
  backbone: false
  embedding: false
  mlp: false
wd: 0.0
