base_dir: '/users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Language/Results/Anaphora_Plural/BERT_Small/Mask_Parameters'
hypothesized_performance: {
  '16' : {
    'high_after_ablation' : '18',
    'low_after_ablation' : '19'
  },
  '17' : {
    'high_after_ablation' : '19',
    'low_after_ablation' : '18'
  }
}