ablation_strategies:
- ''
backbone: resnet50
batch_size_list:
- 32
check_val_every_n_epoch: 1
ckpt_period: 1
data_dir: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Data/Vision
dataset: CVRTDataModule
early_stopping: 1
es_patience: 75
evaluation_type: test
exp_dir: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Vision/Models/Count_Contact/Resnet50/Model_Reporting/49995cc4-ab6b-47f3-99a4-9c2de616c7e9
gpus: 1
l0_components:
  backbone: false
  mlp: false
l0_init_list:
- -1
l0_lambda: -1
l0_stage_list:
- None
log_every_n_steps: 100
lr_list:
- 0.001
max_epochs: 0
max_temp: -1
mlp_dim: 128
mlp_hidden_dim: 2048
n_samples: 10000
n_tasks: 1
num_workers: 1
pretrained_weights:
  backbone: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Vision/Models/Count_Contact/Resnet50/Model_Training/49995cc4-ab6b-47f3-99a4-9c2de616c7e9_backbone.pt
  embedding: false
  mlp: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Vision/Models/Count_Contact/Resnet50/Model_Training/49995cc4-ab6b-47f3-99a4-9c2de616c7e9_mlp.pt
refresh_rate: 10
results_dir: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Vision/Results/Count_Contact/Resnet50/Model_Reporting/49995cc4-ab6b-47f3-99a4-9c2de616c7e9
save_models: false
seed_list:
- 0
task_embedding: 0
test_set: ''
test_tasks:
- '115'
- '116'
- '117'
- '118'
- '119'
- '120'
train_masks:
  backbone: false
  mlp: false
train_task: '115'
train_transform: null
train_weights:
  backbone: false
  embedding: false
  mlp: false
use_last: false
val_transform: null
wd: 0.0
