ablation_strategies:
- zero
- random
- none
backbone: wideresnet50
batch_size_list:
- 64
check_val_every_n_epoch: 1
ckpt_period: 1
data_dir: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Data/Vision/
dataset: CVRTDataModule
early_stopping: 0
es_patience: 0
evaluation_type: test
exp_dir: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Vision/Models/Inside_Contact/WideResnet50/Random_Training/2a63c4d0-5008-45dc-a87c-4409561b6420_T105
gpus: 1
l0_components:
  backbone: true
  mlp: true
l0_init_list:
- 0.0
l0_lambda: 1.0e-08
l0_stage_list:
- - stage_3
  - stage_4
log_every_n_steps: 100
lr_list:
- 0.0001
max_epochs: 90
max_temp: 200
mlp_dim: 128
mlp_hidden_dim: 2048
n_samples: 10000
n_tasks: 1
num_workers: 1
pretrained_weights:
  backbone: false
  embedding: false
  mlp: false
refresh_rate: 10
results_dir: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Vision/Results/Inside_Contact/WideResnet50/Random_Training/2a63c4d0-5008-45dc-a87c-4409561b6420_T105
save_models: false
seed_list:
- 0
- 1
- 2
task_embedding: 0
test_set: ''
test_tasks:
- '103'
- '104'
- '105'
- '106'
- '107'
- '108'
train_masks:
  backbone: true
  mlp: true
train_task: '105'
train_transform: null
train_weights:
  backbone: false
  embedding: false
  mlp: false
use_last: true
val_transform: null
wd: 0.0
