path_db: '../Subnetworks_db/resnet18'
model: 'CNN'
dataset: 'CVRTDataModule'
# trainer
gpus: 1
max_epochs: 120
num_workers: 4
checkpoint: ''
finetune: 0
freeze_pretrained: 0
log_every_n_steps: 100
ckpt_period: 1
seed: -1
early_stopping: 0
refresh_rate: 10
es_patience: 20
check_val_every_n_epoch: 1
#arch
backbone: 'resnet18'
lr: 0.0001
wd: 0.00
n_tasks: 0
mlp_dim: 128
mlp_hidden_dim: 1024
task_embedding: 0
# data
data_dir: '/media/data_cifs_lrs/projects/prj_comp_subnets/comp_data/'
task: '107' # Denotes multitask training
batch_size: 64
train_transform: null
val_transform: null
n_samples: 10000 # 5000, 1000
test_set: ''
exp_name: "Resnet_Comp_Test_Contact"
exp_dir: '../Subnetworks_db/resnet18/Resnet_Comp_Test_Contact'

# Config variables introduced for mask identification
l0_components: {"backbone": False, "mlp": False}
train_masks: {"backbone": False, "mlp": False}
train_weights: {"backbone": False, "mlp": False, "embedding": False}
pretrained_weights: { 
  "backbone": '../Subnetworks_db/resnet18/Resnet_Comp_Training/backbone.pt',
  "mlp": '../Subnetworks_db/resnet18/Resnet_Comp_Training/mlp.pt',
  "embedding": False
  } # False for random initialization
l0_init: -0.2
l0_lambda: .00000001
max_temp: 300
eval_only: True # This is derivable from train_masks and train_weights, but make it explicit with another variable

