LM_init: false
ablation_strategies:
- none
- zero
backbone: BERT_small
batch_size_list:
- 64
check_val_every_n_epoch: 1
ckpt_period: 1
data_dir: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Data/Language
dataset: SyntaxDataModule
early_stopping: 0
es_patience: 0
evaluation_type: test
exp_dir: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Language/Models/Anaphora_Plural/BERT_Small_LM/L0_Reporting/a04b0e46-c394-46a4-8663-378dd8f89674_T16
freeze_until: -1
gpus: 1
l0_components:
  backbone: true
l0_init_list:
- 0.05
l0_lambda: 1.0e-08
l0_stage_list:
- 0
log_every_n_steps: 100
lr_list:
- 0.01
max_epochs: 0
max_temp: 200
model: BERT_small
num_workers: 1
pretrained_weights:
  backbone: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Language/Models/Anaphora_Plural/BERT_Small_LM/Mask_Training/a04b0e46-c394-46a4-8663-378dd8f89674_T16/6346ed7f-ba86-401a-b3f7-9fe0e02fe203_backbone.pt
refresh_rate: 10
results_dir: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Language/Results/Anaphora_Plural/BERT_Small_LM/L0_Reporting/a04b0e46-c394-46a4-8663-378dd8f89674_T16/6346ed7f-ba86-401a-b3f7-9fe0e02fe203_backbone.pt
save_models: false
seed_list:
- 0
test_set: ''
test_tasks:
- '1'
train_masks:
  backbone: false
  mlp: false
train_task: '16'
train_transform: null
train_weights:
  backbone: false
use_last: true
val_transform: null
wd: 0.0
