path_db: '../visr_db/cnn'
model: 'Moco'
dataset: 'CVRTSSLDataModule'
# trainer
gpus: 1
max_epochs: 100
num_workers: 16
checkpoint: ''
log_every_n_steps: 100
ckpt_period: 1
# model
# arch
arch: resnet50
lr: 0.6
momentum: 0.9
weight_decay: 0.000001
moco_dim: 256
moco_mlp_dim: 4096
moco_m: 0.99
moco_m_cos: false
moco_t: 1.0
stop_grad_conv1: false
optimizer: lars
warmup_epochs: 10
# data
data_dir: '/media/data_cifs_lrs/projects/prj_visreason/cvrt_data/'
task: 'a'
batch_size: 1024
train_transform: null
val_transform: null
n_samples: 2500 # 5000, 1000