ablation_strategies:
- zero
- random
- none
backbone: resnet50
batch_size_list:
- 64
check_val_every_n_epoch: 1
ckpt_period: 1
data_dir: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Data/Vision/
dataset: CVRTDataModule
early_stopping: 0
es_patience: 0
evaluation_type: validate
exp_dir: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Vision/Models/Inside_Count/Resnet50/Mask_Parameters/9d495246-75ef-4b88-b382-adcf8c9f2087/111/T111_-0.05_1stage
gpus: 1
l0_components:
  backbone: true
  mlp: true
l0_init_list:
- -0.05
l0_lambda: 1.0e-08
l0_stage_list:
- - stage_4
log_every_n_steps: 100
lr_list:
- 0.01
- 0.0001
max_epochs: 90
max_temp: 200
mlp_dim: 128
mlp_hidden_dim: 2048
n_samples: 10000
n_tasks: 1
num_workers: 1
pretrained_weights:
  backbone: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Vision/Models/Inside_Count/Resnet50/Model_Training/9d495246-75ef-4b88-b382-adcf8c9f2087_backbone.pt
  embedding: false
  mlp: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Vision/Models/Inside_Count/Resnet50/Model_Training/9d495246-75ef-4b88-b382-adcf8c9f2087_mlp.pt
refresh_rate: 10
results_dir: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Vision/Results/Inside_Count/Resnet50/Mask_Parameters/9d495246-75ef-4b88-b382-adcf8c9f2087/111/T111_-0.05_1stage
save_models: false
seed_list:
- 0
task_embedding: 0
test_set: ''
test_tasks:
- '109'
- '110'
- '111'
- '112'
- '113'
- '114'
train_masks:
  backbone: true
  mlp: true
train_task: '111'
train_transform: null
train_weights:
  backbone: false
  embedding: false
  mlp: false
use_last: true
val_transform: null
wd: 0.0
