model: 'BERT_small'
dataset: 'SyntaxDataModule'
# trainer
gpus: 1
max_epochs: 100
num_workers: 1
log_every_n_steps: 100
ckpt_period: 1
seed_list: [0]
early_stopping: 1
refresh_rate: 10
es_patience: 30
check_val_every_n_epoch: 1
#arch
backbone: 'BERT_small'
lr_list: [0.01, 0.001, 0.0001, 0.00001]
wd: 0.00
# data 
data_dir: '/users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Data/Language'
train_task: '10'
test_tasks: ['10']
batch_size_list: [32, 64]
train_transform: null
val_transform: null
test_set: ''
exp_dir: '/users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Language/Models/Anaphora_Singular/BERT_Small_LM/Model_Hyperparameters'
results_dir: '/users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Language/Results/Anaphora_Singular/BERT_Small_LM/Model_Hyperparameters'

# Config variables introduced for mask identification
l0_components: {"backbone": False}
train_masks: {"backbone": False}
train_weights: {"backbone": True}
pretrained_weights: { 
  "backbone": "prajjwal1/bert-small",
  } # False for random initialization
l0_init_list: [-1]
l0_lambda: -1
max_temp: -1
l0_stage_list: [-1]
ablation_strategies: ["None"]
evaluation_type: "validate"
LM_init: True # Denotes whether to initialize the model with pretrained LM parameters
freeze_until: -1
save_models: False
use_last: False
