LM_init: false
ablation_strategies:
- none
- zero
backbone: BERT_small
batch_size_list:
- 64
check_val_every_n_epoch: 1
ckpt_period: 1
data_dir: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Data/Language
dataset: SyntaxDataModule
early_stopping: 0
es_patience: 0
evaluation_type: test
exp_dir: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Language/Models/Anaphora_Plural/BERT_Small/L0_Reporting/88284354-139d-4bf9-a7f6-bd3e682d45ba_T17
freeze_until: -1
gpus: 1
l0_components:
  backbone: true
l0_init_list:
- -0.05
l0_lambda: 1.0e-08
l0_stage_list:
- 2
log_every_n_steps: 100
lr_list:
- 0.0001
max_epochs: 0
max_temp: 200
model: BERT_small
num_workers: 1
pretrained_weights:
  backbone: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Language/Models/Anaphora_Plural/BERT_Small/Mask_Training/88284354-139d-4bf9-a7f6-bd3e682d45ba_T17/2cfc7ca0-621b-4223-9e17-74b52610bcbc_backbone.pt
refresh_rate: 10
results_dir: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Language/Results/Anaphora_Plural/BERT_Small/L0_Reporting/88284354-139d-4bf9-a7f6-bd3e682d45ba_T17/2cfc7ca0-621b-4223-9e17-74b52610bcbc_backbone.pt
save_models: false
seed_list:
- 0
test_set: ''
test_tasks:
- '1'
train_masks:
  backbone: false
  mlp: false
train_task: '17'
train_transform: null
train_weights:
  backbone: false
use_last: true
val_transform: null
wd: 0.0
