LM_init: false
ablation_strategies:
- zero
- random
- none
backbone: BERT_small
batch_size_list:
- 64
check_val_every_n_epoch: 1
ckpt_period: 1
data_dir: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Data/Language
dataset: SyntaxDataModule
early_stopping: 0
es_patience: 0
evaluation_type: test
exp_dir: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Language/Models/Anaphora_Singular/BERT_Small/Random_Training/d028ecec-e016-441a-be9c-3351f6f9d271_T12
freeze_until: -1
gpus: 1
l0_components:
  backbone: true
l0_init_list:
- 0.0
l0_lambda: 1.0e-08
l0_stage_list:
- 0
log_every_n_steps: 100
lr_list:
- 0.0001
max_epochs: 90
max_temp: 200
model: BERT_small
num_workers: 1
pretrained_weights:
  backbone: false
refresh_rate: 10
results_dir: /users/mlepori/data/mlepori/projects/Compositional_Subnetworks/Language/Results/Anaphora_Singular/BERT_Small/Random_Training/d028ecec-e016-441a-be9c-3351f6f9d271_T12
save_models: false
seed_list:
- 0
- 1
- 2
test_set: ''
test_tasks:
- '10'
- '11'
- '12'
- '13'
- '14'
train_masks:
  backbone: true
train_task: '12'
train_transform: null
train_weights:
  backbone: false
use_last: true
val_transform: null
wd: 0.0
